[versions]
agp = "8.4.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.8.0"
navigationFragmentKtx = "2.9.4"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

